### ISSUE TITLE
Cannot find RTSP-Server-1.1.8.aar (com.github.pedroSG94:RTSP-Server:1.1.8).

### ISSUE THREAD

**Issue by zde-nekz** [pedroSG94/RTSP-Server#99]
After complete reinstall of Android studio I am unable to build project anymore. I get

Configuration cache state could not be cached: field `elements` of `org.gradle.configurationcache.serialization.codecs.ResolutionBackedFileCollectionSpec` bean found in field `runtimeDependencies` of task `:app:dataBindingMergeDependencyArtifactsAnnieDebug` of type `com.android.build.gradle.internal.tasks.databinding.DataBindingMergeDependencyArtifactsTask`: error writing value of type 'java.util.ArrayList'
> Could not find RTSP-Server-1.1.8.aar (com.github.pedroSG94:RTSP-Server:1.1.8).
  Searched in the following locations:
      https://jitpack.io/com/github/pedroSG94/RTSP-Server/1.1.8/RTSP-Server-1.1.8.aar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Dependency is added to module build.gradle 
`implementation("com.github.pedroSG94:RTSP-Server:1.1.8")`
 and jitpack is also added to settings.gradle.kts

```
dependencyResolutionManagement {
...
 repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
..
}
..
}
```

**Comment by pedroSG94** [comment]
Hello,

version 1.1.8 is currently in status OK in jitpack so it should be working and I can resolve the build gradle.

I think that the problem is related with your gradle because you are trying to resolve this url:


> Could not find RTSP-Server-1.1.8.aar (com.github.pedroSG94:RTSP-Server:1.1.8).
> Searched in the following locations:
> https://jitpack.io/com/github/pedroSG94/RTSP-Server/1.1.8/RTSP-Server-1.1.8.aar

But check the URL. This URL:
 https://jitpack.io/com/github/pedroSG94/RTSP-Server/1.1.8/RTSP-Server-1.1.8.aar
 Should be:
 https://jitpack.io/com/github/pedroSG94/RTSP-Server/1.1.8

As you can see opening both in a browser the first one (your configured url in the gradle) can't be found because it is wrong but int the second you can resolve it

**Comment by zde-nekz** [comment]
I have created new Android studio project with this dependency. Please check on https://github.com/zde-nekz/rtspTestApp. Error is still the same.

**Comment by KurtH96** [comment]
This issue also occurs with 1.1.7. Making a new project is not a feasible action in my situation. Following the instructions to include dependencies from here on GitHub or on Jitpack does not resolve the problem. This was not an issue a week ago.

**Comment by KurtH96** [comment]
@pedroSG94 My project is building again with the master branch. I would prefer a stable release.

@zde-nekz The following dependency works for me if you're looking to just have your project compile.
`implementation 'com.github.pedroSG94:RTSP-Server:master'`

**Comment by pedroSG94** [comment]
Hello,

I did an update of the library with last dependencies and It is working with the project shared. Try with the version 1.1.9

**Comment by zde-nekz** [comment]
It is working fine, thank you.
